[package]
name = "ya-exe-api"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
actix = "0.9"
futures = "0.3"
log = "0.4"
serde_json = "1.0"
thiserror = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.bus]
version = "0.2"
package = "ya-service-bus"
