[package]
name = "ya-runtime-api"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default=[]
server=['prost']

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.31"
log = "0.4.8"

prost = { version = "0.6.1", optional = true }

[build-dependencies]
prost-build = "0.6.0"